<?php
$checks = [
    'mysqli' => extension_loaded('mysqli'),
    'curl' => extension_loaded('curl'),
    'openssl' => extension_loaded('openssl'),
    'mbstring' => extension_loaded('mbstring'),
];

$xamppRoot = realpath(__DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..');
$paths = [
    'htdocs' => $xamppRoot . DIRECTORY_SEPARATOR . 'htdocs',
    'tmp' => $xamppRoot . DIRECTORY_SEPARATOR . 'tmp',
    'apache logs' => $xamppRoot . DIRECTORY_SEPARATOR . 'apache' . DIRECTORY_SEPARATOR . 'logs',
];

$pathChecks = [];
foreach ($paths as $label => $path) {
    $exists = is_dir($path);
    $writable = $exists ? is_writable($path) : false;
    $pathChecks[$label] = [
        'path' => $path,
        'exists' => $exists,
        'writable' => $writable,
    ];
}

$timezone = date_default_timezone_get();
$now = date('Y-m-d H:i:s');
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>XAMPP Workspace Health</title>
    <style>
        :root {
            --bg: #f4f7fb;
            --panel: #ffffff;
            --ink: #1f2937;
            --muted: #6b7280;
            --ok: #0f766e;
            --bad: #b91c1c;
            --line: #d1d5db;
            --accent: #1d4ed8;
        }

        * { box-sizing: border-box; }

        body {
            margin: 0;
            font-family: "Segoe UI", Tahoma, sans-serif;
            background: linear-gradient(145deg, #eaf2ff 0%, #f7fbff 55%, #eef9f2 100%);
            color: var(--ink);
            min-height: 100vh;
            display: grid;
            place-items: center;
            padding: 24px;
        }

        .card {
            width: min(920px, 100%);
            background: var(--panel);
            border: 1px solid #e5e7eb;
            border-radius: 16px;
            box-shadow: 0 18px 44px rgba(17, 24, 39, 0.12);
            overflow: hidden;
        }

        .header {
            padding: 22px 24px;
            border-bottom: 1px solid var(--line);
            background: linear-gradient(120deg, #eff6ff 0%, #f0fdf4 100%);
        }

        .header h1 {
            margin: 0;
            font-size: clamp(1.3rem, 2.7vw, 1.85rem);
            letter-spacing: 0.01em;
        }

        .header p {
            margin: 8px 0 0;
            color: var(--muted);
        }

        .grid {
            display: grid;
            gap: 16px;
            padding: 20px 24px 26px;
        }

        @media (min-width: 780px) {
            .grid { grid-template-columns: 1fr 1fr; }
        }

        section {
            border: 1px solid var(--line);
            border-radius: 12px;
            padding: 14px 14px 8px;
        }

        h2 {
            margin-top: 0;
            font-size: 1rem;
            color: var(--accent);
        }

        ul {
            list-style: none;
            margin: 0;
            padding: 0;
        }

        li {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            gap: 10px;
            border-top: 1px dashed #e5e7eb;
            padding: 10px 0;
        }

        li:first-child {
            border-top: 0;
            padding-top: 2px;
        }

        .label {
            font-weight: 600;
        }

        .value {
            text-align: right;
            color: var(--muted);
            font-family: Consolas, monospace;
            max-width: 56%;
            word-break: break-word;
        }

        .status-ok { color: var(--ok); font-weight: 700; }
        .status-bad { color: var(--bad); font-weight: 700; }

        .quick-link {
            display: inline-block;
            margin-top: 10px;
            padding: 8px 12px;
            border-radius: 10px;
            text-decoration: none;
            font-weight: 700;
            color: #0f172a;
            background: #dbeafe;
            border: 1px solid #bfdbfe;
        }
    </style>
</head>
<body>
    <main class="card">
        <header class="header">
            <h1>XAMPP Workspace Health</h1>
            <p>Generated by Copilot Chat coding task sample</p>
            <a class="quick-link" href="db-check.php">Open MySQL Connection Check</a>
            <a class="quick-link" href="../index.php" style="background:#e0f2fe;border-color:#bae6fd;">Back to Project Hub</a>
        </header>

        <div class="grid">
            <section>
                <h2>Runtime</h2>
                <ul>
                    <li><span class="label">PHP Version</span><span class="value"><?= htmlspecialchars(PHP_VERSION, ENT_QUOTES, 'UTF-8') ?></span></li>
                    <li><span class="label">Server Time</span><span class="value"><?= htmlspecialchars($now, ENT_QUOTES, 'UTF-8') ?></span></li>
                    <li><span class="label">Timezone</span><span class="value"><?= htmlspecialchars($timezone, ENT_QUOTES, 'UTF-8') ?></span></li>
                    <li><span class="label">Project Path</span><span class="value"><?= htmlspecialchars(__DIR__, ENT_QUOTES, 'UTF-8') ?></span></li>
                </ul>
            </section>

            <section>
                <h2>PHP Extensions</h2>
                <ul>
                    <?php foreach ($checks as $name => $ok): ?>
                    <li>
                        <span class="label"><?= htmlspecialchars($name, ENT_QUOTES, 'UTF-8') ?></span>
                        <span class="value <?= $ok ? 'status-ok' : 'status-bad' ?>"><?= $ok ? 'Loaded' : 'Missing' ?></span>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </section>

            <section style="grid-column: 1 / -1;">
                <h2>Directory Access</h2>
                <ul>
                    <?php foreach ($pathChecks as $name => $state): ?>
                    <li>
                        <span class="label"><?= htmlspecialchars($name, ENT_QUOTES, 'UTF-8') ?></span>
                        <span class="value">
                            <?= htmlspecialchars($state['path'], ENT_QUOTES, 'UTF-8') ?><br>
                            <span class="<?= $state['exists'] ? 'status-ok' : 'status-bad' ?>">
                                <?= $state['exists'] ? 'Exists' : 'Missing' ?>
                            </span>
                            |
                            <span class="<?= $state['writable'] ? 'status-ok' : 'status-bad' ?>">
                                <?= $state['writable'] ? 'Writable' : 'Not writable' ?>
                            </span>
                        </span>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </section>
        </div>
    </main>
</body>
</html>
