# cPanel DynamicUI configuration for 7ink.com.au
# Copy this file to:
# /usr/local/cpanel/base/frontend/jupiter/dynamicui/dynamicui_sevenink.conf

item=7ink.com.au
file=sevenink/index.html.tt
group=domains
type=item
id=sevenink
order=10000
showfiller=1
